on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}  # Your FTP server
          username: ${{ secrets.FTP_USERNAME }}  # Your FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password from secrets
          server-dir: /  # Destination directory on the server
          protocol: ftp  # Start with FTP
          log-level: verbose  # Enable verbose logging for debugging
